### PR TITLE
Updates to zig 0.9.0

### PR DESCRIPTION
**Pull request by jacoscaz**
Hi! I am very new to Zig and I have very little idea of what I am doing as I had never touched anything Zig (or C, for that matter) up until a couple of hours ago. 

That said, I've tried running a couple of examples from this repo using the latest Zig nightly build and got a few compilation errors. Guessing I was looking at issues brought by the changes in the latest versions of Zig I thought I'd try my hand at updating the code.

So far I got the following examples working:

- [ ] tilescript
- [x] tilemap
- [x] editor
- [x] texture_packer_cli
- [x] texture_packer
- [X] empty
- [x] offscreen_rendering
- [X] todo
- [x] docking

Questions:

1. what to do with the missing  `edge.zig` file imported by `src/math/rect.zig`?
2. unused params such as `fn hello(world: T) {}` should be ignored using `fn hello(_: T) {}` or `fn hello(world: T) { _ = world; }`?

### CODE REVIEW

**Comment by prime31** [comment]
The commits are looking good to me so far! To answer your questions:
1. Edge struct is below
2. It’s probably cleaner and easier to do `fn hello(_: T)`

```zig

pub const Edge = enum(u8) {
    right,
    left,
    top,
    bottom,

    pub fn opposing(self: Edge) Edge {
        return switch (self) {
            .right => .left,
            .left => .right,
            .top => .bottom,
            .bottom => .top,
        };
    }

    pub fn horizontal(self: Edge) bool {
        return self == .right or self == .left;
    }

    pub fn vertical(self: Edge) bool {
        return self == .top or self == .bottom;
    }

    pub fn max(self: Edge) bool {
        return self == .right or self == .bottom;
    }
};
```

**Comment by jacoscaz** [comment]
Thank you!

WRT ignoring unused parameters, turns out that it's not currently possible to use `_` multiple times as a way to ignore unused params (although I think Zig is moving in that direction). I guess I'll have to keep using a mix of both!

**Comment by jacoscaz** [comment]
Got all examples working with the exception of `tilescript`, for which I am getting a `error: evaluation exceeded 1000 backwards branches`. I guess it has something to do with infinite recursion/looping but my understanding of Zig is not quite there yet. I'm moving to using `zig-upaya` for a little project of mine and hopefully come back here with a higher degree of competency. Feel free to comment upon this PR if you'd like me to change anything or merge this in, I'll open a new one for `tilescript` if/when I get around to it.

**Comment by prime31** [comment]
Looks good! Thanks! The tilescript issue probably just needs a `@setEvalBranchQuota` call so the compiler doesnt give up.

**Pull request merged**
